-- Users table seeds here (Example)
INSERT INTO users (name, email, password, phone_number, address, city, post_code, province, country) VALUES ('John Doe', 'john.doe@example.com', 'password123', '123-456-7890', '123 Main St', 'Anytown', 'A1B 2C3', 'ON', 'Canada');
INSERT INTO users (name, email, password, phone_number, address, city, post_code, province, country) VALUES ('Jane Smith', 'jane.smith@example.com', 'password456', '987-654-3210', '456 Elm St', 'Anycity', 'X1Y 3Z9', 'BC', 'Canada');
INSERT INTO users (name, email, password, phone_number, address, city, post_code, province, country) VALUES ('Alice Johnson', 'alice.johnson@example.com', 'password789', '555-123-4567', '789 Oak St', 'Anyvillage', 'M1N 4P6', 'ON', 'Canada');
INSERT INTO users (name, email, password, phone_number, address, city, post_code, province, country) VALUES ('Bob Brown', 'bob.brown@example.com', 'passwordabc', '222-333-4444', '321 Pine St', 'Anysuburb', 'V7R 3N5', 'BC', 'Canada');
INSERT INTO users (name, email, password, phone_number, address, city, post_code, province, country) VALUES ('Eva Martinez', 'eva.martinez@example.com', 'passwordxyz', '777-888-9999', '654 Maple St', 'Anysmalltown', 'T5J 2V5', 'AB', 'Canada');
INSERT INTO users (name, email, password, phone_number, address, city, post_code, province, country) VALUES ('Michael Lee', 'michael.lee@example.com', 'password123', '111-222-3333', '987 Cedar St', 'Anylargecity', 'K1P 5H9', 'ON', 'Canada');
INSERT INTO users (name, email, password, phone_number, address, city, post_code, province, country) VALUES ('Sara White', 'sara.white@example.com', 'password456', '444-555-6666', '369 Birch St', 'Anylargetown', 'H2W 1S8', 'QC', 'Canada');
INSERT INTO users (name, email, password, phone_number, address, city, post_code, province, country) VALUES ('David Taylor', 'david.taylor@example.com', 'password789', '888-999-0000', '852 Walnut St', 'Anysmallcity', 'S4P 3Y2', 'SK', 'Canada');
INSERT INTO users (name, email, password, phone_number, address, city, post_code, province, country) VALUES ('Karen Adams', 'karen.adams@example.com', 'passwordabc', '666-777-8888', '741 Ash St', 'Anylargevillage', 'E3B 5G5', 'NB', 'Canada');
INSERT INTO users (name, email, password, phone_number, address, city, post_code, province, country) VALUES ('Peter Wilson', 'peter.wilson@example.com', 'passwordxyz', '333-444-5555', '963 Poplar St', 'Anybigcity', 'L1V 1A1', 'ON', 'Canada');
